
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action ClearAction;
	private global::Gtk.Action UpperCaseAction;
	private global::Gtk.Action LowerCaseAction;
	private global::Gtk.Action SaveAction;
	private global::Gtk.Action ClearallAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action _Open;
	private global::Gtk.Action C_lose;
	private global::Gtk.Action E_xit;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action _Help;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button ButtonClear;
	private global::Gtk.Button buttonUpper;
	private global::Gtk.Button buttonLower;
	private global::Gtk.Button button4;
	private global::Gtk.TextView textview1;
	private global::Gtk.ScrolledWindow scrolledwindow1;
	private global::Gtk.TextView logTextView;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ClearAction = new global::Gtk.Action ("ClearAction", global::Mono.Unix.Catalog.GetString ("Clear"), null, null);
		this.ClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear");
		w1.Add (this.ClearAction, null);
		this.UpperCaseAction = new global::Gtk.Action ("UpperCaseAction", global::Mono.Unix.Catalog.GetString ("Upper Case"), null, null);
		this.UpperCaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Upper Case");
		w1.Add (this.UpperCaseAction, null);
		this.LowerCaseAction = new global::Gtk.Action ("LowerCaseAction", global::Mono.Unix.Catalog.GetString ("Lower Case"), null, null);
		this.LowerCaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Lower Case");
		w1.Add (this.LowerCaseAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.ClearallAction = new global::Gtk.Action ("ClearallAction", global::Mono.Unix.Catalog.GetString ("Clearall"), null, null);
		this.ClearallAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clearall");
		w1.Add (this.ClearallAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, "<Alt>f");
		this._Open = new global::Gtk.Action ("_Open", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this._Open.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this._Open, "<Control>o");
		this.C_lose = new global::Gtk.Action ("C_lose", global::Mono.Unix.Catalog.GetString ("Close"), null, null);
		this.C_lose.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.C_lose, "<Control>l");
		this.E_xit = new global::Gtk.Action ("E_xit", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.E_xit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.E_xit, "<Control>x");
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.HelpAction, null);
		this._Help = new global::Gtk.Action ("_Help", global::Mono.Unix.Catalog.GetString ("About...."), null, null);
		this._Help.ShortLabel = global::Mono.Unix.Catalog.GetString ("About....");
		w1.Add (this._Help, "<Control>h");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='_Open' action='_Open'/><menuitem name='C_lose' action='C_lose'/><menuitem name='E_xit' action='E_xit'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='_Help' action='_Help'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ButtonClear = new global::Gtk.Button ();
		this.ButtonClear.CanFocus = true;
		this.ButtonClear.Name = "ButtonClear";
		this.ButtonClear.UseUnderline = true;
		this.ButtonClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
		this.hbox1.Add (this.ButtonClear);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonClear]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonUpper = new global::Gtk.Button ();
		this.buttonUpper.CanFocus = true;
		this.buttonUpper.Name = "buttonUpper";
		this.buttonUpper.UseUnderline = true;
		this.buttonUpper.Label = global::Mono.Unix.Catalog.GetString ("Upper Case");
		this.hbox1.Add (this.buttonUpper);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonUpper]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonLower = new global::Gtk.Button ();
		this.buttonLower.CanFocus = true;
		this.buttonLower.Name = "buttonLower";
		this.buttonLower.UseUnderline = true;
		this.buttonLower.Label = global::Mono.Unix.Catalog.GetString ("Lower Case");
		this.hbox1.Add (this.buttonLower);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonLower]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.hbox1.Add (this.button4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button4]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.vbox1.Add (this.textview1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.textview1]));
		w8.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.logTextView = new global::Gtk.TextView ();
		this.logTextView.CanFocus = true;
		this.logTextView.Name = "logTextView";
		this.logTextView.Editable = false;
		this.logTextView.CursorVisible = false;
		this.scrolledwindow1.Add (this.logTextView);
		this.vbox1.Add (this.scrolledwindow1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
		w10.Position = 3;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1142;
		this.DefaultHeight = 609;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ClearallAction.Activated += new global::System.EventHandler (this.OnClearallActionActivated);
		this._Open.Activated += new global::System.EventHandler (this.OnOpenActivated);
		this.C_lose.Activated += new global::System.EventHandler (this.OnCLoseActivated);
		this.E_xit.Activated += new global::System.EventHandler (this.OnEXitActivated);
		this._Help.Activated += new global::System.EventHandler (this.OnHelpActivated);
		this.ButtonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		this.buttonUpper.Clicked += new global::System.EventHandler (this.OnButtonUpperClicked);
		this.buttonLower.Clicked += new global::System.EventHandler (this.OnButtonLowerClicked);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
	}
}
